# Generated by Django 4.0.6 on 2022-07-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mika', '0002_mikaproductlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mikaproductlinks',
            options={'verbose_name': 'MikaProductLinks', 'verbose_name_plural': 'MikaProductLinks'},
        ),
    ]
