# Generated by Django 4.0.6 on 2022-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mika', '0004_mikaproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikaFinalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=20000, null=True)),
                ('sku', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'MikaFinalProducts',
                'verbose_name_plural': 'MikaFinalProductss',
            },
        ),
    ]
