# Generated by Django 4.0.6 on 2022-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opalnet', '0002_opalnetproductlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpalnetFinalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=20000, null=True)),
                ('sku', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'OpalnetFinalProducts',
                'verbose_name_plural': 'OpalnetFinalProductss',
            },
        ),
    ]
