# Generated by Django 4.0.6 on 2022-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Opalnet', '0003_opalnetfinalproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opalnetfinalproducts',
            options={'verbose_name': 'OpalnetFinalProducts', 'verbose_name_plural': 'OpalnetFinalProducts'},
        ),
    ]
