# Generated by Django 4.0.6 on 2022-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotpoint', '0002_hotpointproductlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpointproductlinks',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
