# Generated by Django 4.0.6 on 2022-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hypermart', '0002_hypermartproductlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypermartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=20000, null=True)),
                ('brand', models.CharField(blank=True, max_length=20000, null=True)),
                ('sku', models.CharField(blank=True, max_length=20000, null=True)),
                ('product_link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'HypermartProducts',
                'verbose_name_plural': 'HypermartProducts',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
