# Generated by Django 4.0.6 on 2022-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_products_image_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samutech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True, max_length=10000, null=True)),
                ('price', models.TextField(blank=True, max_length=10000, null=True)),
                ('brand', models.TextField(blank=True, max_length=10000, null=True)),
                ('barcode', models.TextField(blank=True, max_length=10000, null=True)),
                ('sku', models.TextField(blank=True, max_length=10000, null=True)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamutechCategories2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('crawled', models.BooleanField(default=False)),
            ],
        ),
    ]
