# Generated by Django 4.0.6 on 2022-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_samutech_samutechcategories2'),
    ]

    operations = [
        migrations.AddField(
            model_name='samutechcategories2',
            name='product_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
