# Generated by Django 4.0.6 on 2022-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_samutechcategories2_product_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='samutechcategories2',
            name='product_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
